# Generated by Django 4.1 on 2023-11-30 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100, verbose_name='物件名')),
                ('address', models.CharField(max_length=100, verbose_name='住所')),
                ('area', models.CharField(max_length=100, verbose_name='地域')),
                ('deposit_key_money', models.CharField(max_length=20, verbose_name='敷金/礼金')),
                ('year_built', models.IntegerField(verbose_name='築年数')),
                ('phone_number', models.IntegerField(verbose_name='電話番号')),
                ('picture_url', models.FileField(upload_to='property_main/', verbose_name='トップ画像')),
                ('station', models.CharField(max_length=1000, verbose_name='沿線')),
                ('walk_minute', models.IntegerField(verbose_name='徒歩')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'property',
            },
        ),
        migrations.CreateModel(
            name='PropertyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(max_length=100, verbose_name='間取り')),
                ('area', models.IntegerField(verbose_name='面積')),
                ('rent', models.IntegerField(verbose_name='賃料')),
                ('credit', models.BooleanField(default=True, help_text='否の場合False', verbose_name='クレジット決済')),
                ('management_fee', models.IntegerField(verbose_name='管理費')),
                ('floor', models.IntegerField(verbose_name='階')),
                ('room_number', models.IntegerField(verbose_name='部屋番号')),
                ('position', models.CharField(max_length=50, verbose_name='位置')),
                ('remarks', models.CharField(max_length=1000, verbose_name='備考')),
                ('property_tour_url', models.URLField(verbose_name='内見')),
                ('purchase_status', models.BooleanField(default=True, help_text='契約済ならFalse', verbose_name='契約状況')),
                ('parking_flg', models.BooleanField(default=True, help_text='否の場合False', verbose_name='駐車場有無情報')),
                ('pet_flg', models.BooleanField(default=True, help_text='否の場合False', verbose_name='ペット可否情報')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.property', verbose_name='物件')),
            ],
            options={
                'db_table': 'property_detail',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=1000, verbose_name='タイプ')),
            ],
            options={
                'db_table': 'property_type',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=20, verbose_name='区名')),
            ],
            options={
                'db_table': 'ward',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100, verbose_name='設備・サービス')),
                ('property_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.propertydetail')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='PropertyPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='property_detail_picture/')),
                ('order', models.IntegerField()),
                ('property_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.propertydetail')),
            ],
            options={
                'db_table': 'property_detail_picture',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.propertytype', verbose_name='物件の種類'),
        ),
        migrations.AddField(
            model_name='property',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.ward', verbose_name='区'),
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.CharField(max_length=100, verbose_name='その他')),
                ('property_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.propertydetail')),
            ],
            options={
                'db_table': 'other',
            },
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen', models.CharField(max_length=100, verbose_name='キッチン')),
                ('property_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.propertydetail')),
            ],
            options={
                'db_table': 'kitchen',
            },
        ),
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom', models.CharField(max_length=100, verbose_name='バス・トイレ')),
                ('property_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.propertydetail')),
            ],
            options={
                'db_table': 'bathroom',
            },
        ),
    ]
