# Generated by Django 4.1 on 2023-12-05 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='area',
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=50, verbose_name='条件')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.property', verbose_name='物件')),
            ],
            options={
                'db_table': 'condition',
            },
        ),
    ]
