# Generated by Django 4.1 on 2024-02-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0002_remove_property_area_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertydetail",
            name="layout_img",
            field=models.FileField(
                default="/media/layout_img/no-img.png", upload_to="layout_img/"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="picture_url",
            field=models.FileField(
                default="/media/layout_img/no-img.png",
                upload_to="property_main/",
                verbose_name="トップ画像",
            ),
        ),
    ]
