# Generated by Django 4.1 on 2024-02-07 04:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0003_propertydetail_layout_img"),
        ("stores", "0003_propertydetail_layout_img_alter_property_picture_url"),
    ]

    operations = []
