# Generated by Django 4.1 on 2024-02-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0004_merge_20240207_0428"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="電話番号"),
        ),
        migrations.AlterField(
            model_name="propertydetail",
            name="layout_img",
            field=models.FileField(
                default="/media/layout_img/no-img.png", upload_to="layout_img/"
            ),
        ),
    ]
