# Generated by Django 4.1 on 2023-11-30 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='メールアドレス')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='名前')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='国籍')),
                ('religion', models.CharField(blank=True, max_length=50, null=True, verbose_name='宗教')),
                ('self_introduction', models.CharField(blank=True, max_length=1000, null=True, verbose_name='自己紹介')),
                ('job', models.CharField(blank=True, max_length=50, null=True, verbose_name='職業')),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='profile/', verbose_name='プロフィール画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('contract_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.property', verbose_name='契約物件')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
