# Generated by Django 4.1 on 2024-01-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.BooleanField(blank=True, null=True, verbose_name="性別"),
        ),
    ]
