# Generated by Django 4.1 on 2024-01-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="性別"
            ),
        ),
    ]
