# Generated by Django 4.1 on 2024-02-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_user_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contract",
            field=models.FileField(
                blank=True, null=True, upload_to="contract/", verbose_name="契約申請書"
            ),
        ),
    ]
