# Generated by Django 5.2.11 on 2026-03-01 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '設備カテゴリ',
                'verbose_name_plural': '設備カテゴリ',
                'db_table': 'amenity_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '都道府県',
                'verbose_name_plural': '都道府県',
                'db_table': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('station', models.CharField(help_text='最寄り駅名', max_length=100)),
                ('line', models.CharField(help_text='沿線名', max_length=100)),
                ('walk_minute', models.PositiveSmallIntegerField(help_text='駅からの徒歩分数')),
                ('year_built', models.PositiveSmallIntegerField(help_text='築年（西暦）')),
                ('phone_number', models.CharField(max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='property_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '物件',
                'verbose_name_plural': '物件',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '物件種別',
                'verbose_name_plural': '物件種別',
                'db_table': 'property_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.amenitycategory')),
            ],
            options={
                'verbose_name': '設備',
                'verbose_name_plural': '設備',
                'db_table': 'amenities',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='表示順（小さい順）')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': '物件画像',
                'verbose_name_plural': '物件画像',
                'db_table': 'property_images',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.propertytype'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('floor', models.PositiveSmallIntegerField()),
                ('layout', models.CharField(help_text='1K, 2LDK etc.', max_length=20)),
                ('layout_image', models.ImageField(blank=True, null=True, upload_to='layout_images/')),
                ('area', models.DecimalField(decimal_places=2, help_text='専有面積（㎡）', max_digits=6)),
                ('rent', models.PositiveIntegerField(help_text='賃料（円）')),
                ('management_fee', models.PositiveIntegerField(default=0, help_text='管理費（円）')),
                ('deposit_months', models.PositiveSmallIntegerField(default=0, help_text='敷金（賃料の何ヶ月分）')),
                ('key_money_months', models.PositiveSmallIntegerField(default=0, help_text='礼金（賃料の何ヶ月分）')),
                ('credit_card_ok', models.BooleanField(default=True)),
                ('parking', models.BooleanField(default=False)),
                ('pet_allowed', models.BooleanField(default=False)),
                ('position', models.CharField(blank=True, help_text='向き（南向き等）', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('tour_url', models.URLField(blank=True, help_text='外部VR内見URL')),
                ('has_3d_model', models.BooleanField(default=False, help_text='3Dモデルが存在するかどうか。Trueの部屋のみ3Dボタンを表示する。')),
                ('availability', models.CharField(choices=[('available', '空室'), ('reserved', '予約中'), ('contracted', '契約済')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
            options={
                'verbose_name': '部屋',
                'verbose_name_plural': '部屋',
                'db_table': 'units',
                'ordering': ['property', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='UnitAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.amenity')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.unit')),
            ],
            options={
                'db_table': 'unit_amenities',
                'unique_together': {('unit', 'amenity')},
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='amenities',
            field=models.ManyToManyField(blank=True, through='properties.UnitAmenity', to='properties.amenity'),
        ),
        migrations.CreateModel(
            name='UnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='unit_images/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='表示順（小さい順）')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.unit')),
            ],
            options={
                'verbose_name': '部屋画像',
                'verbose_name_plural': '部屋画像',
                'db_table': 'unit_images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='properties.city')),
            ],
            options={
                'verbose_name': '区市町村',
                'verbose_name_plural': '区市町村',
                'db_table': 'wards',
                'ordering': ['city', 'name'],
                'unique_together': {('city', 'name')},
            },
        ),
        migrations.AddField(
            model_name='property',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.ward'),
        ),
    ]
