# Generated by Django 5.2.11 on 2026-03-01 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField(help_text='希望内見日')),
                ('message', models.TextField(blank=True, help_text='管理会社へのメッセージ（任意）')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('confirmed', '確定'), ('completed', '完了'), ('cancelled', 'キャンセル')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_requests', to='properties.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '内見予約',
                'verbose_name_plural': '内見予約',
                'db_table': 'viewing_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
