# Generated by Django 4.1 on 2024-02-14 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=50, verbose_name="タイトル")),
                ("comment", models.TextField(max_length=1000, verbose_name="本文")),
                (
                    "dashboard_picture",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="dashboard/",
                        verbose_name="掲示板画像",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="送信者",
                    ),
                ),
            ],
            options={
                "db_table": "article",
                "ordering": ("-created_at",),
            },
        ),
    ]
